/**
* NavBar include
* ------------------
*/

(function(){
	var str='';
	str+='	<!-- ====================================== -->';
	str+='	<!-- Start of navbar -->';
	str+='	<!-- ====================================== -->';
	str+='	<header id="header">';
	str+='		<!-- navbar -->';
	str+='		<nav class="navbar"><!-- toggleClass : over -->';
	str+='			<div class="dimm"></div>';
	str+='			<div class="container-fluid">';
	str+='				<!-- logo -->';
	str+='				<div class="logo">';
	str+='					<a href="javascript:void(0);" class="logo" aria-label="Career DOOSAN HOME"><span class="blind">Career DOOSAN</span></a>';
	str+='				</div>';
	str+='				<!-- //logo -->';
	str+='				<!-- navbar-gnb : pc size view-->';
	str+='				<div class="navbar-gnb">';
	str+='					<div class="gnb-bg"></div>';
	str+='					<ul class="nav gnb">';
	str+='						<li><!-- toggleClass : active -->';
	str+='							<a href="javascript:void(0);" role="button"><span>내일을 준비하는</span></a>';
	str+='							<div class="collapse"><!-- toggleClass : show -->';
	str+='								<ul class="nav">';
	str+='									<li class="outlink"><a href="javascript:void(0);"><span>두산의 인재, 두산인</span></a></li>';
	str+='									<li><!-- toggleClass : active -->';
	str+='										<a href="javascript:void(0);"><span>	두산인의 하루</span></a>';
	str+='									</li>';
	str+='									<li><a href="javascript:void(0);"><span>생생 두산 입사기</span></a></li>';
	str+='									<li><a href="javascript:void(0);"><span>두산인의 혜택</span></a></li>';
	str+='								</ul>';
	str+='							</div>';
	str+='						</li>';
	str+='						<li>';
	str+='							<a href="javascript:void(0);" role="button"><span>두산에 대하여</span></a>';
	str+='							<div class="collapse">';
	str+='								<ul class="nav">';
	str+='									<li class="outlink"><a href="javascript:void(0);"><span>두산스토리</span></a></li>';
	str+='									<li class="outlink"><a href="javascript:void(0);"><span>두산의 활약상</span></a></li>';
	str+='									<li class="outlink"><a href="javascript:void(0);"><span>목표와 핵심가치</span></a></li>';
	str+='									<li class="outlink"><a href="javascript:void(0);"><span>경영전략</span></a></li>';
	str+='									<li class="outlink"><a href="javascript:void(0);"><span>두산뉴스룸</span></a></li>';
	str+='								</ul>';
	str+='							</div>';
	str+='						</li>';
	str+='						<li>';
	str+='							<a href="javascript:void(0);" role="button"><span>직무 알아보고</span></a>';
	str+='							<div class="collapse">';
	str+='								<ul class="nav">';
	str+='									<li><a href="javascript:void(0);"><span>계열사로 보기</span></a></li>';
	str+='									<li><a href="javascript:void(0);"><span>직무순으로 보기</span></a></li>';
	str+='									<li><a href="javascript:void(0);"><span>직무 온라인상담</span></a></li>';
	str+='								</ul>';
	str+='							</div>';
	str+='						</li>';
	str+='						<li>';
	str+='							<a href="javascript:void(0);" role="button"><span>입사지원하기</span></a>';
	str+='							<div class="collapse">';
	str+='								<ul class="nav">';
	str+='									<li><a href="javascript:void(0);"><span>채용절차</span></a></li>';
	str+='									<li><a href="javascript:void(0);"><span>채용공고</span></a></li>';
	str+='									<li><a href="javascript:void(0);"><span>인재DB</span></a></li>';
	str+='									<li><a href="javascript:void(0);"><span>FAQ</span></a></li>';
	str+='									<li><a href="javascript:void(0);"><span>공지사항</span></a></li>';
	str+='								</ul>';
	str+='							</div>';
	str+='						</li>';
	str+='					</ul>';
	str+='				</div>';
	str+='				<!-- //navbar-gnb -->';
	str+='				<!-- navbar-util -->';
	str+='				<div class="navbar-util">';
	str+='					<!-- Login  -->';
	str+='					<ul class="nav gnb-util">';
	str+='						<li>';
	str+='							<!-- 로그인이전 -->';
	str+='							<!-- <a href="javascript:void(0);" role="button" class="btn-login"><span>로그인</span></a> -->';
	str+='							<!-- //로그인이전 -->';
	str+='							<!-- 로그인 이후 -->';
	str+='							<div>';
	str+='								<span class="name">김두산님</span>';
	str+='								<a href="javascript:void(0);" role="button" class="btn-logout"><span>로그아웃</span></a>';
	str+='								<div class="my-menu">';
	str+='									<a href="javascript:void(0)" role="button" class="btn-my" id="myMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>MY</span></a>';
	str+='									<div class="dropdown-menu dropdown-my" aria-labelledby="myMenuLink">';
	str+='										<a class="dropdown-item" href="javascript:void(0);"><span>입사지원 수정</span></a>';
	str+='										<a class="dropdown-item" href="javascript:void(0);"><span>전형결과 확인</span></a>';
	str+='										<a class="dropdown-item" href="javascript:void(0);"><span>나의 관심직무</span></a>';
	str+='										<a class="dropdown-item" href="javascript:void(0);"><span>개인정보 수정</span></a>';
	str+='										<a class="dropdown-item" href="javascript:void(0);"><span>서류반환 청구</span></a>';
	str+='									</div>';
	str+='								</div>';
	str+='							</div>';
	str+='							<!-- //로그인 이후 -->';
	str+='						</li>';
	str+='						<li>';
	str+='							<button type="button" id="sidebarToggleBtn" class="btn-top-nav" aria-label="Toggle Nav"></button>';
	str+='						</li>';
	str+='					</ul>';
	str+='				</div>';
	str+='				<!-- //navbar-util -->';
	str+='				<!-- navbar-location -->';
	str+='				<div class="navbar-location">';
	str+='					<div class="location-wrap">';
	str+='						<div class="location active"><!-- toggleClass : active, down -->';
	str+='							<h3><a href="javascript:void(0);" role="button" class="blind">내일을 준비하는</a></h3>';
	str+='							<ul class="nav">';
	str+='								<li><a href="javascript:void(0);"><span>두산의 인재, 두산인</span></a></li>';
	str+='								<li><!-- toggleClass : active -->';
	str+='									<a href="javascript:void(0);"><span>	두산인의 하루</span></a>';
	str+='								</li>';
	str+='								<li><a href="javascript:void(0);"><span>생생 두산 입사기</span></a></li>';
	str+='								<li><a href="javascript:void(0);"><span>두산인의 혜택</span></a></li>';
	str+='							</ul>';
	str+='						</div>';
	str+='						<div class="location ">';
	str+='							<h3><a href="javascript:void(0);" role="button" class="blind">두산에 대하여</a></h3>';
	str+='							<ul class="nav">';
	str+='								<li><a href="javascript:void(0);"><span>두산스토리</span></a></li>';
	str+='								<li><a href="javascript:void(0);"><span>두산의 활약상</span></a></li>';
	str+='								<li><a href="javascript:void(0);"><span>목표와 핵심가치</span></a></li>';
	str+='								<li><a href="javascript:void(0);"><span>경영전략</span></a></li>';
	str+='								<li><a href="javascript:void(0);"><span>두산뉴스룸</span></a></li>';
	str+='							</ul>';
	str+='						</div>';
	str+='						<div class="location ">';
	str+='							<h3><a href="javascript:void(0);" role="button" class="blind">직무 알아보고</a></h3>';
	str+='							<ul class="nav">';
	str+='								<li><a href="javascript:void(0);"><span>계열사로 보기</span></a></li>';
	str+='								<li><a href="javascript:void(0);"><span>직무순으로 보기</span></a></li>';
	str+='								<li><a href="javascript:void(0);"><span>직무 온라인상담</span></a></li>';
	str+='							</ul>';
	str+='						</div>';
	str+='						<div class="location ">';
	str+='							<h3><a href="javascript:void(0);" role="button" class="blind">입사지원하기</a></h3>';
	str+='							<ul class="nav">';
	str+='								<li><a href="javascript:void(0);"><span>채용절차</span></a></li>';
	str+='								<li><a href="javascript:void(0);"><span>채용공고</span></a></li>';
	str+='								<li><a href="javascript:void(0);"><span>인재DB</span></a></li>';
	str+='								<li><a href="javascript:void(0);"><span>FAQ</span></a></li>';
	str+='								<li><a href="javascript:void(0);"><span>공지사항</span></a></li>';
	str+='							</ul>';
	str+='						</div>';
	str+='						<div class="location ">';
	str+='							<h3><a href="javascript:void(0);" role="button" class="blind">마이페이지</a></h3>';
	str+='							<ul class="nav">';
	str+='								<li><a href="javascript:void(0);"><span>입사지원 수정</span></a></li>';
	str+='								<li><a href="javascript:void(0);"><span>전형결과 확인</span></a></li>';
	str+='								<li><a href="javascript:void(0);"><span>나의 관심직무</span></a></li>';
	str+='								<li><a href="javascript:void(0);"><span>개인정보 수정</span></a></li>';
	str+='								<li><a href="javascript:void(0);"><span>서류반환 청구</span></a></li>';
	str+='							</ul>';
	str+='						</div>';
	str+='					</div>';
	str+='				</div>';
	str+='				<!-- //navbar-location -->';
	str+='			</div>';
	str+='		</nav>';
	str+='		<!-- //navbar -->';
	str+='	</header>';
	str+='	<!-- ====================================== -->';
	str+='	<!-- //End of navbar -->';
	str+='	<!-- ====================================== -->';
	document.write(str);
})();



